Repository brito1212/software-project-management, pull requests merged in 2024-11, with the labels that each got.

#12 feat: Tela perfil e editar perfil
  backend/midias/user/urls.py
  backend/midias/user/views.py
  frontend/index.html
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/app/store.ts
  frontend/src/assets/icons/edit-icon.svg
  frontend/src/components/Header.tsx
  frontend/src/components/forms/Input.module.css
  frontend/src/components/helper/ProtectedRoute.tsx
  frontend/src/components/icons/EditIcon.tsx
  frontend/src/components/profile/EditProfile.module.css
  frontend/src/components/profile/EditProfile.tsx
  frontend/src/components/profile/EditProfileModal.module.css
  frontend/src/components/profile/EditProfileModal.tsx
  frontend/src/components/profile/ListProfile.module.css
  frontend/src/components/profile/ListProfile.tsx
  frontend/src/components/profile/UserProfile.module.css
  frontend/src/components/profile/UserProfile.tsx
  frontend/src/features/ui/uiSlice.ts
  frontend/src/features/user/user.type.ts
  frontend/src/features/user/userApi.ts
  frontend/src/features/user/userSlice.ts
  frontend/src/pages/Profile.tsx
Labels: Release 01

#18 Feat/create review
  backend/midias/review/migrations/0002_alter_review_rate.py
  backend/midias/review/migrations/0003_comment_created_at_review_created_at.py
  backend/midias/review/models.py
  backend/midias/review/serializers.py
  backend/midias/review/views.py
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Carousel.tsx
  frontend/src/components/Media/viewMedia.tsx
  frontend/src/components/forms/Input.tsx
  frontend/src/components/login/LoginForm.tsx
  frontend/src/components/profile/EditProfile.tsx
  frontend/src/components/review/CreateReview.module.css
  frontend/src/components/review/CreateReview.tsx
  frontend/src/components/review/DeleteReview.module.css
  frontend/src/components/review/DeleteReview.tsx
  frontend/src/components/review/ListReview.module.css
  frontend/src/components/review/ListReview.tsx
  frontend/src/features/media/mediaApi.ts
  frontend/src/features/review/review.type.ts
  frontend/src/features/review/reviewApi.ts
  frontend/src/features/review/reviewSlice.ts
  frontend/src/features/ui/uiSlice.ts
  frontend/src/pages/Media.tsx
  frontend/src/pages/SignUp.tsx
Labels: Release 02

#27 Feat/visit profile
  backend/midias/user/views.py
  frontend/src/App.tsx
  frontend/src/components/Header.module.css
  frontend/src/components/Header.tsx
  frontend/src/components/forms/SearchField.module.css
  frontend/src/components/forms/SearchField.tsx
  frontend/src/components/list/AllListsView.tsx
  frontend/src/components/profile/ListProfile.module.css
  frontend/src/components/profile/ListProfile.tsx
  frontend/src/components/profile/UserProfile.module.css
  frontend/src/components/profile/UserProfile.tsx
  frontend/src/components/profile/VisitProfile.module.css
  frontend/src/components/profile/VisitProfile.tsx
  frontend/src/features/user/userApi.ts
  frontend/src/pages/Profile.tsx
Labels: enhancement, Release 03

#29 feat: mostrar amigos no menu lateral
  frontend/src/components/Aside.tsx
  frontend/src/components/Header.tsx
  frontend/src/components/forms/SearchField.tsx
  frontend/src/features/user/user.type.ts
  frontend/src/features/user/userApi.ts
  frontend/src/pages/Profile.tsx
Labels: enhancement
